# Generated by Django 3.0.7 on 2020-09-15 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('countryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationApp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxNumberOfSeats', models.IntegerField()),
                ('tableNumber', models.IntegerField()),
                ('restaurantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationApp.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfSeats', models.IntegerField()),
                ('reservationTime', models.DateTimeField()),
                ('expiredReservationTime', models.DateTimeField()),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationApp.Table')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
